### ISSUE TITLE
Form import error

### ISSUE THREAD

**Issue by lemac889** [nhatkhai/pcbfab2solidwork#2]
Hello, thanks for your work on this macro.
I got a error on load form file.
There is the error log for the file FrmStatus.log:
Line 2: Property OleObjectBlob in FrmStatus could not be set.
Sorry I don't have the skill to suggest a fix or to test something.

**Comment by nhatkhai** [comment]
I'm not sure what the error about. If there are some pic, and a explain about how to repeat the error. But base on the title, you seem to got error from import the vb Form file. This may be the VB version you having in your system is not compatible with the macro.

**Comment by lemac889** [comment]
This is the error that I get when I try to import the .frm like FrmStatus.frm into my new macro:
![2019-11-18 13_17_59-SOLIDWORKS 2018 SP5 0](https://user-images.githubusercontent.com/7817580/69078607-34caaa00-0a06-11ea-8457-b30da2252f24.png)
![2019-11-18 13_18_08-SOLIDWORKS 2018 SP5 0](https://user-images.githubusercontent.com/7817580/69078638-4449f300-0a06-11ea-986c-8dcdbcfc9b01.png)
![2019-11-18 13_18_18-SOLIDWORKS 2018 SP5 0](https://user-images.githubusercontent.com/7817580/69078643-4744e380-0a06-11ea-8227-c525d2471932.png)
![2019-11-18 13_18_54-libs](https://user-images.githubusercontent.com/7817580/69078649-4c099780-0a06-11ea-8425-4334496239ec.png)
![2019-11-18 13_19_11-C__Users_Takuser_Downloads_pcbfab2solidwork-master_macros_libs_FrmStatus log - N](https://user-images.githubusercontent.com/7817580/69078653-4dd35b00-0a06-11ea-9b5d-bc3e50dbe1be.png)

**Comment by nhatkhai** [comment]
Look like you have a "dirty" environment base on the last image. May be try some of the following:
* Try save your project and restart the Solidwork (to make sure no VB form are actively running)
* May be redo all of this from a clean Solidworks project like in the demo video to make sure what known work would work first.

So fart these problem seem to not be a problems from the macro design but the VB + Solidworks work flow issue.
